// <auto-generated />
using System;
using FilesStorageModels.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilesStorageModels.Migrations
{
    [DbContext(typeof(FilesStorageContext))]
    partial class FilesStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilesStorageModels.DataModels.FilesCategorie", b =>
                {
                    b.Property<string>("Categorie")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Categorie");

                    b.ToTable("FilesCategorie");
                });

            modelBuilder.Entity("FilesStorageModels.DataModels.UsersApp", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(8);

                    b.Property<bool>("Activo")
                        .HasColumnType("BIT")
                        .HasColumnOrder(10);

                    b.Property<string>("Apellido")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("DATETIME")
                        .HasColumnOrder(9);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdRol")
                        .HasColumnType("INT")
                        .HasColumnOrder(2);

                    b.Property<string>("Nombre")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(6);

                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(5);

                    b.HasKey("Email");

                    b.ToTable("UsersApp");
                });

            modelBuilder.Entity("FilesStorageModels.DataModels.UsersRol", b =>
                {
                    b.Property<string>("Rol")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Rol");

                    b.ToTable("UsersRol");
                });
#pragma warning restore 612, 618
        }
    }
}
